// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW2XRLk1sjTgcD-1KU7FF4IF6B-7NXcq0',
    appId: '1:679013999464:android:0fbcfc1a7a7bfe4357acdd',
    messagingSenderId: '679013999464',
    projectId: 'pintar-care-v3-5f8c4',
    storageBucket: 'pintar-care-v3-5f8c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc9MjvKzNSRyo-Cygi1Vh3vTvurTqAcrg',
    appId: '1:679013999464:ios:fe0b48d17b5b9aa057acdd',
    messagingSenderId: '679013999464',
    projectId: 'pintar-care-v3-5f8c4',
    storageBucket: 'pintar-care-v3-5f8c4.firebasestorage.app',
    iosBundleId: 'com.buf.pintarr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc9MjvKzNSRyo-Cygi1Vh3vTvurTqAcrg',
    appId: '1:679013999464:ios:fe0b48d17b5b9aa057acdd',
    messagingSenderId: '679013999464',
    projectId: 'pintar-care-v3-5f8c4',
    storageBucket: 'pintar-care-v3-5f8c4.firebasestorage.app',
    iosBundleId: 'com.buf.pintarr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1jHA1RssdClVSvFmeVCRYhuHxv-_PzZo',
    appId: '1:679013999464:web:2c58acc281c6819457acdd',
    messagingSenderId: '679013999464',
    projectId: 'pintar-care-v3-5f8c4',
    authDomain: 'pintar-care-v3-5f8c4.firebaseapp.com',
    storageBucket: 'pintar-care-v3-5f8c4.firebasestorage.app',
    measurementId: 'G-YB6ERPCTNS',
  );
}
